### ISSUE TITLE
test_05_tiledata_resource_get fails

### ISSUE THREAD

**Issue by privong** [allegro/tipboard#26]
I have been working on setting up a flipboard instance, with some success. But the line_chart and norm_chart tiles have been giving me trouble. I have been getting the following error:

```
Tile aptwxhistP configuration error:
Error
No data specified
```

I tried running the test suites:
```
$ tipboard test
Raven is not configured (logging is disabled). Please see the documentation for more information.
test_collecting_tiles_data (test_config_parser.TestConfigFiles) ... ok
test_finding_configs_files (test_config_parser.TestConfigFiles) ... ok
test_get_rows (test_config_parser.TestConfigParser)
simple call of get_rows method and check rows count ... ok
test_get_rows_cols_validator (test_config_parser.TestConfigParser) ... ok
test_01_api_key (test_rest_api.TestRestApi) ... ok
test_02_info_resource (test_rest_api.TestRestApi) ... ok
test_03_push_resource (test_rest_api.TestRestApi) ... ok
test_04_tileconfig_resource_post (test_rest_api.TestRestApi) ... ok
test_05_tiledata_resource_get (test_rest_api.TestRestApi) ... ERROR
test_06_tileconfig_resource_delete (test_rest_api.TestRestApi) ... ok
test_07_tiledata_resource_delete (test_rest_api.TestRestApi) ... ok
test_all_files_created (test_console_commands.TestConfigFiles) ... ok
test_config_contains_api_key (test_console_commands.TestConfigFiles)
check if 'settings-local.py' contains API key ... ok
test_config_contains_project_name (test_console_commands.TestConfigFiles)
check if 'settings-local.py' contains project's name ... ok
test_recreate_project (test_console_commands.TestConfigFiles) ... ok

======================================================================
ERROR: test_05_tiledata_resource_get (test_rest_api.TestRestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dashboard/tb-env/lib/python2.7/site-packages/tipboard/tests/test_rest_api.py", line 135, in test_05_tiledata_resource_get
    '%Y-%m-%d %H:%M:%S')
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2015-07-18T00:16:27-00:00' does not match format '%Y-%m-%d %H:%M:%S'

----------------------------------------------------------------------
Ran 15 tests in 4.172s

FAILED (errors=1)
```

If I modify the comparison string in the test_rest_api.py file to include the "T" between the date and time, and re-run the test, I get the following output:

```
$ tipboard test
Raven is not configured (logging is disabled). Please see the documentation for more information.
test_collecting_tiles_data (test_config_parser.TestConfigFiles) ... ok
test_finding_configs_files (test_config_parser.TestConfigFiles) ... ok
test_get_rows (test_config_parser.TestConfigParser)
simple call of get_rows method and check rows count ... ok
test_get_rows_cols_validator (test_config_parser.TestConfigParser) ... ok
test_01_api_key (test_rest_api.TestRestApi) ... ok
test_02_info_resource (test_rest_api.TestRestApi) ... ok
test_03_push_resource (test_rest_api.TestRestApi) ... ok
test_04_tileconfig_resource_post (test_rest_api.TestRestApi) ... ok
test_05_tiledata_resource_get (test_rest_api.TestRestApi) ... ERROR
test_06_tileconfig_resource_delete (test_rest_api.TestRestApi) ... ok
test_07_tiledata_resource_delete (test_rest_api.TestRestApi) ... ok
test_all_files_created (test_console_commands.TestConfigFiles) ... ok
test_config_contains_api_key (test_console_commands.TestConfigFiles)
check if 'settings-local.py' contains API key ... ok
test_config_contains_project_name (test_console_commands.TestConfigFiles)
check if 'settings-local.py' contains project's name ... ok
test_recreate_project (test_console_commands.TestConfigFiles) ... ok

======================================================================
ERROR: test_05_tiledata_resource_get (test_rest_api.TestRestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dashboard/tb-env/lib/python2.7/site-packages/tipboard/tests/test_rest_api.py", line 135, in test_05_tiledata_resource_get
    '%Y-%m-%dT%H:%M:%S')
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: -00:00

----------------------------------------------------------------------
Ran 15 tests in 4.116s

FAILED (errors=1)
```

I am running Tipboard 1.4.0 (installed with pip) on Arch Linux on a Raspberry Pi B (v1). The Redis server is v=3.0.2.

For what is is worth, other tiles (```simple_percentage```, ```text```, ```fancy_listing```, ```cumulative_flow```) seem to work fine.

**Comment by privong** [comment]
For what it's worth, the issue I was having with line_chart and norm_chart was a json formatting issue (received a 200 response, but the data weren't correctly parsable). So that issue is unrelated to this test failing.
